@startuml

class AuthController
class RecordController
class AdminController

class AuthService
class MFAService
class RecordService
class AccessControlService
class AuditLogger

class UserRepository
class RecordRepository
class AuditRepository

class MFAFactory
interface MFAStrategy
class EmailOTPStrategy
class TOTPStrategy

class User
class MedicalRecord
class SecurityEvent

AuthController --> AuthService
RecordController --> RecordService
AdminController --> AuditLogger

AuthService --> UserRepository
AuthService --> MFAService
AuthService --> AuditLogger

MFAService --> MFAFactory
MFAFactory --> MFAStrategy
MFAStrategy <|.. EmailOTPStrategy
MFAStrategy <|.. TOTPStrategy

RecordService --> RecordRepository
RecordService --> AccessControlService
RecordService --> AuditLogger

AuditLogger --> AuditRepository

UserRepository --> User
RecordRepository --> MedicalRecord
AuditRepository --> SecurityEvent

@enduml